demoform/demoform/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

demoform/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_post, name='add'),
    path('save/', views.save_post, name='save'),
]

demoform/news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=1000, blank=False, null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())

demoform/news/forms.py
from django import forms
from .models import Post

# Create your forms here.

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'time_create',)

demoform/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm

# Create your views here.

def index(request):
    return HttpResponse("Hello everyone!")

def add_post(request):
    f = PostForm()
    return render(request, 'news/add_post.html', { "f": f })

def save_post(request):
    if request.method == "POST":
        data = PostForm(request.POST)
        if data.is_valid():
            data.save()
            return HttpResponse('Save successfully')
        else:
            return HttpResponse('Invalid form')
    else:
        return HttpResponse('Invalid post request')

demoform/news/templates/news/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add new post</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
        {% csrf_token %}
        <div>
            {{ f.title }}
        </div>
        <br>
        <div>
            {{ f.content }}
        </div>
        <br>
        <div>
            {{ f.time_create }}
        </div>
        <br>
        <input type="submit" value="Add post">
    </form>
</body>
</html>